# Generated by Django 2.2.7 on 2019-11-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
