# Generated by Django 2.2.7 on 2019-11-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0002_auto_20191121_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='checkIn_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='checkOut_time',
            field=models.DateTimeField(),
        ),
    ]
