# Generated by Django 2.2.7 on 2019-11-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0003_auto_20191125_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='checkIn_time',
            field=models.DateTimeField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='checkOut_time',
            field=models.DateTimeField(default=False),
        ),
    ]
