# Generated by Django 2.2.7 on 2019-11-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0004_auto_20191125_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='checkIn_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='checkOut_time',
            field=models.DateTimeField(null=True),
        ),
    ]
