# Generated by Django 2.2.7 on 2019-11-25 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0005_auto_20191125_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 12, 55, 3, 161894)),
        ),
    ]
