# Generated by Django 2.2.7 on 2019-11-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0006_visit_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='created_on',
        ),
    ]
