# Generated by Django 2.2.7 on 2019-11-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0008_visitor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='image',
        ),
    ]
