# Generated by Django 2.2.7 on 2019-11-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0009_remove_visitor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
