# Generated by Django 2.2.7 on 2019-11-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0013_auto_20191126_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='image',
        ),
    ]
