# Generated by Django 2.2.7 on 2019-12-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0014_remove_visitor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='image',
            field=models.FilePathField(blank=True, path='/gallery'),
        ),
    ]
